alias vim='nvim'
alias ll='ls -alh'
alias clip='xclip -selection clipboard -i <'
alias rg='rg --hidden -n'
#alias update='sudo zypper update -y && sudo zypper dup -y'
#alias avante='nvim -c "lua vim.defer_fn(function()require(\"avante.api\").zen_mode()end, 100)"'
#alias rg='rg --hidden -n'
#alias rgi='rg --hidden -ni'
